defaults:
  - metrics/binary_accuracy
  - metrics/binary_confusion_matrix
  - metrics/binary_auroc
  #- metrics/mrr
  - metrics/binary_precision
  - metrics/binary_recall

_target_: torchmetrics.MetricCollection
# since MetricCollection does not recognize OmegaConf containers as their corresponding Python primitives
# force the conversion of OmegaConf containers to Python primitives
_convert_: all
