defaults:
  - metrics/cldice
  - metrics/betti_error_1
  - metrics/binary_dice
  - metrics/ccdice
  - metrics/betti_error_0

_target_: torchmetrics.MetricCollection
# since MetricCollection does not recognize OmegaConf containers as their corresponding Python primitives
# force the conversion of OmegaConf containers to Python primitives
_convert_: all
