# This custom sweeper tries to emulate closely the syntax of Hydra's built-in BasicSweeper
# https://hydra.cc/docs/tutorials/basic/running_your_app/multi-run/#sweeping-via-hydrasweeperparams

# The keys indicate the config nodes to sweep over, in dot-notation
# The values define how to sweep, and have to be one of the sweep overrides defined by Hydra
# https://hydra.cc/docs/advanced/override_grammar/extended/#sweeps

params:
  data.split_idx: range(${oc.select:data.split.n_splits,1}) # By default, sweep over the number of splits, or 1 if not defined

# If the experiment return a value, e.g. a performance metric, `reduce` defines how to aggregate over the sweep
reduce:
  _target_: numpy.nanmean
