# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: ??? # no sane default can be provided here, data is set in `experiment` config
  - model: ??? # no sane default can be provided here, model is set in `experiment` config
  - reconstruction: default # no sane default can be provided here, reconstruction is set in `experiment` config
  - callbacks: default
  - logger: wandb # set logger here or use command line (e.g. `python train.py logger=wandb`)
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  # serial sweeper is a custom sweeper that emulates the syntax of Hydra's built-in BasicSweeper
  # to run multiple experiments in serial in the same process, e.g. cross-validation
  - serial_sweeper: null

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: edge_level_prediction

  # config for hyperparameter optimization
  - hparams_search: null

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

# task name, determines output directory path
task_name: "infer"

# tags to help you identify your experiments
tags:
  - "infer"

# simply provide checkpoint path to resume training
ckpt_path: ???

# seed for random number generators in pytorch, numpy and python.random
seed: null
